{{ config(
    materialized='table'
) }}

SELECT
    MD5(CUSTOMER_ID) AS CUSTOMER_KEY,

    CUSTOMER_ID,
    GENDER,
    SENIOR_CITIZEN,
    PARTNER,
    DEPENDENTS,
    TENURE,

    CASE
        WHEN TENURE = 0 THEN 'NEW'
        WHEN TENURE <= 12 THEN '0-1 YEAR'
        WHEN TENURE <= 36 THEN '1-3 YEARS'
        WHEN TENURE <= 60 THEN '3-5 YEARS'
        ELSE '5+ YEARS'
    END AS TENURE_SEGMENT,

    PHONE_SERVICE,
    MULTIPLE_LINES,
    INTERNET_SERVICE,
    ONLINE_SECURITY,
    ONLINE_BACKUP,
    DEVICE_PROTECTION,
    TECH_SUPPORT,
    STREAMING_TV,
    STREAMING_MOVIES,
    CONTRACT,
    PAPERLESS_BILLING,
    PAYMENT_METHOD,
    MONTHLY_CHARGES,
    TOTAL_CHARGES,

    CASE
        WHEN TRIM(CHURN) = 'Yes' THEN TRUE
        WHEN TRIM(CHURN) = 'No' THEN FALSE
        ELSE NULL
    END AS IS_CHURNED,

    LOAD_DATE

FROM {{ ref('stg_customers') }}