{{ config(
    materialized='table'
) }}

WITH customers AS (
    SELECT * FROM {{ ref('stg_customers') }}
),

ticket_summary AS (
    SELECT
        CUSTOMER_ID,
        COUNT(TICKET_ID) AS TOTAL_SUPPORT_TICKETS,
        AVG(SATISFACTION_SCORE) AS AVG_CSAT_SCORE
    FROM {{ ref('stg_support_tickets') }}
    GROUP BY CUSTOMER_ID
)

SELECT
    MD5(c.CUSTOMER_ID) AS CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.GENDER,
    c.SENIOR_CITIZEN,
    c.HAS_PARTNER,
    c.HAS_DEPENDENTS,
    c.TENURE_MONTHS,

    CASE
        WHEN c.TENURE_MONTHS = 0 THEN '00. New Subscriber'
        WHEN c.TENURE_MONTHS <= 12 THEN '01. 0 - 1 Year'
        WHEN c.TENURE_MONTHS <= 24 THEN '02. 1 - 2 Years'
        WHEN c.TENURE_MONTHS <= 48 THEN '03. 2 - 4 Years'
        ELSE '04. 4+ Years'
    END AS TENURE_COHORT,

    c.HAS_PHONE_SERVICE,
    c.MULTIPLE_LINES,
    c.INTERNET_SERVICE,
    c.ONLINE_SECURITY,
    c.ONLINE_BACKUP,
    c.DEVICE_PROTECTION,
    c.TECH_SUPPORT,
    c.STREAMING_TV,
    c.STREAMING_MOVIES,

    -- Count active premium services
    (
        CASE WHEN c.ONLINE_SECURITY = 'Yes' THEN 1 ELSE 0 END +
        CASE WHEN c.ONLINE_BACKUP = 'Yes' THEN 1 ELSE 0 END +
        CASE WHEN c.DEVICE_PROTECTION = 'Yes' THEN 1 ELSE 0 END +
        CASE WHEN c.TECH_SUPPORT = 'Yes' THEN 1 ELSE 0 END +
        CASE WHEN c.STREAMING_TV = 'Yes' THEN 1 ELSE 0 END +
        CASE WHEN c.STREAMING_MOVIES = 'Yes' THEN 1 ELSE 0 END
    ) AS ACTIVE_SERVICES_COUNT,

    c.CONTRACT,
    c.HAS_PAPERLESS_BILLING,
    c.PAYMENT_METHOD,
    c.MONTHLY_CHARGES,
    c.TOTAL_CHARGES,

    c.CHURN,
    c.CHURN_FLAG,
    CASE WHEN c.CHURN_FLAG = 1 THEN TRUE ELSE FALSE END AS IS_CHURNED,

    COALESCE(t.TOTAL_SUPPORT_TICKETS, 0) AS TOTAL_SUPPORT_TICKETS,
    ROUND(t.AVG_CSAT_SCORE, 2) AS AVG_CSAT_SCORE,

    c.LOAD_DATE

FROM customers c
LEFT JOIN ticket_summary t
    ON c.CUSTOMER_ID = t.CUSTOMER_ID