{{ config(
    materialized='table'
) }}

WITH towers AS (
    SELECT * FROM {{ ref('stg_towers') }}
),

outages_agg AS (
    SELECT
        TOWER_ID,
        COUNT(OUTAGE_ID) AS LIFETIME_OUTAGES_COUNT,
        SUM(DURATION_MINUTES) AS TOTAL_DOWNTIME_MINUTES,
        SUM(ESTIMATED_IMPACTED_USERS) AS TOTAL_SUBSCRIBERS_IMPACTED
    FROM {{ ref('stg_network_outages') }}
    GROUP BY TOWER_ID
)

SELECT
    MD5(t.TOWER_ID) AS TOWER_KEY,
    t.TOWER_ID,
    t.TOWER_NAME,
    t.CITY,
    t.STATE,
    t.LATITUDE,
    t.LONGITUDE,
    t.TECHNOLOGY,
    t.VENDOR,
    t.CAPACITY,
    t.INSTALLATION_DATE,
    t.STATUS,
    t.IS_ACTIVE,

    COALESCE(o.LIFETIME_OUTAGES_COUNT, 0) AS LIFETIME_OUTAGES_COUNT,
    COALESCE(o.TOTAL_DOWNTIME_MINUTES, 0) AS TOTAL_DOWNTIME_MINUTES,
    COALESCE(o.TOTAL_SUBSCRIBERS_IMPACTED, 0) AS TOTAL_SUBSCRIBERS_IMPACTED,

    ROUND(
        100.0 - (COALESCE(o.TOTAL_DOWNTIME_MINUTES, 0) * 100.0 / (365 * 24 * 60)),
        3
    ) AS UPTIME_AVAILABILITY_PCT,

    t.LOAD_DATE

FROM towers t
LEFT JOIN outages_agg o
    ON t.TOWER_ID = o.TOWER_ID
