{{ config(
    materialized='table'
) }}

WITH towers AS (
    SELECT * FROM {{ ref('dim_towers') }}
),

usage_summary AS (
    SELECT
        TOWER_ID,
        COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_SUBSCRIBERS,
        SUM(DATA_USAGE_GB) AS TOTAL_DATA_SERVED_GB,
        SUM(VOICE_MINUTES) AS TOTAL_VOICE_MINUTES,
        AVG(DATA_USAGE_GB) AS AVG_DATA_PER_EVENT_GB
    FROM {{ ref('fct_daily_usage') }}
    GROUP BY TOWER_ID
)

SELECT
    t.TOWER_KEY,
    t.TOWER_ID,
    t.TOWER_NAME,
    t.CITY,
    t.STATE,
    t.TECHNOLOGY,
    t.VENDOR,
    t.CAPACITY,
    t.STATUS,
    t.IS_ACTIVE,
    t.LIFETIME_OUTAGES_COUNT,
    t.TOTAL_DOWNTIME_MINUTES,
    t.TOTAL_SUBSCRIBERS_IMPACTED,
    t.UPTIME_AVAILABILITY_PCT,

    COALESCE(u.DISTINCT_SUBSCRIBERS, 0) AS RECENT_ACTIVE_USERS,
    ROUND(COALESCE(u.TOTAL_DATA_SERVED_GB, 0), 2) AS TOTAL_DATA_SERVED_GB,
    COALESCE(u.TOTAL_VOICE_MINUTES, 0) AS TOTAL_VOICE_MINUTES,

    -- Network load utilization index
    ROUND(
        (COALESCE(u.DISTINCT_SUBSCRIBERS, 0) * 100.0 / NULLIF(t.CAPACITY, 0)),
        2
    ) AS CAPACITY_UTILIZATION_PCT,

    CURRENT_TIMESTAMP() AS MART_REFRESH_TIMESTAMP

FROM towers t
LEFT JOIN usage_summary u
    ON t.TOWER_ID = u.TOWER_ID
