-- ==============================================================================
-- TELECOM DATA PLATFORM — SNOWFLAKE INFRASTRUCTURE SETUP
-- SCRIPT 03: RAW Layer Table Definitions & COPY INTO Ingestion
-- ==============================================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;
USE SCHEMA RAW;

-- ------------------------------------------------------------------------------
-- 1. RAW TABLES DDL
-- ------------------------------------------------------------------------------

-- 1.1 Customers (CRM Feed)
CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
    CUSTOMER_ID         STRING,
    GENDER              STRING,
    SENIOR_CITIZEN      NUMBER(1,0),
    PARTNER             STRING,
    DEPENDENTS          STRING,
    TENURE              NUMBER(5,0),
    PHONE_SERVICE       STRING,
    MULTIPLE_LINES      STRING,
    INTERNET_SERVICE    STRING,
    ONLINE_SECURITY     STRING,
    ONLINE_BACKUP       STRING,
    DEVICE_PROTECTION   STRING,
    TECH_SUPPORT        STRING,
    STREAMING_TV        STRING,
    STREAMING_MOVIES    STRING,
    CONTRACT            STRING,
    PAPERLESS_BILLING   STRING,
    PAYMENT_METHOD      STRING,
    MONTHLY_CHARGES     NUMBER(10,2),
    TOTAL_CHARGES       STRING,
    CHURN               STRING,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.2 Master Plans Catalog
CREATE TABLE IF NOT EXISTS RAW_PLANS (
    PLAN_ID             STRING,
    PLAN_NAME           STRING,
    MONTHLY_PRICE       NUMBER(10,2),
    DATA_LIMIT_GB       NUMBER(10,0),
    NETWORK_TYPE        STRING,
    VOICE_MINUTES       NUMBER(10,0),
    SMS_LIMIT           NUMBER(10,0),
    VALIDITY_DAYS       NUMBER(5,0),
    PLAN_CATEGORY       STRING,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.3 Cell Towers Network Infrastructure
CREATE TABLE IF NOT EXISTS RAW_TOWERS (
    TOWER_ID            STRING,
    TOWER_NAME          STRING,
    CITY                STRING,
    STATE               STRING,
    LATITUDE            NUMBER(10,6),
    LONGITUDE           NUMBER(10,6),
    TECHNOLOGY          STRING,
    VENDOR              STRING,
    CAPACITY            NUMBER(10,0),
    INSTALLATION_DATE   DATE,
    STATUS              STRING,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.4 Customer Billing Cycles
CREATE TABLE IF NOT EXISTS RAW_BILLING (
    BILL_ID             STRING,
    CUSTOMER_ID         STRING,
    BILLING_PERIOD      STRING,
    BILL_DATE           DATE,
    DUE_DATE            DATE,
    BASE_AMOUNT         NUMBER(10,2),
    ADDITIONAL_CHARGES  NUMBER(10,2),
    DISCOUNT_AMOUNT     NUMBER(10,2),
    TAX_AMOUNT          NUMBER(10,2),
    TOTAL_AMOUNT        NUMBER(10,2),
    PAYMENT_STATUS      STRING,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.5 Payment Transactions
CREATE TABLE IF NOT EXISTS RAW_PAYMENTS (
    PAYMENT_ID          STRING,
    BILL_ID             STRING,
    CUSTOMER_ID         STRING,
    PAYMENT_DATETIME    TIMESTAMP_NTZ,
    AMOUNT              NUMBER(10,2),
    PAYMENT_METHOD      STRING,
    PAYMENT_GATEWAY     STRING,
    TRANSACTION_STATUS  STRING,
    TRANSACTION_REF     STRING,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.6 Cellular Usage Records
CREATE TABLE IF NOT EXISTS RAW_USAGE (
    USAGE_ID            STRING,
    CUSTOMER_ID         STRING,
    USAGE_DATE          DATE,
    TOWER_ID            STRING,
    VOICE_MINUTES       NUMBER(10,0),
    DATA_USAGE_MB       NUMBER(12,2),
    DATA_USAGE_GB       NUMBER(12,3),
    SMS_COUNT           NUMBER(10,0),
    IS_ROAMING          BOOLEAN,
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.7 Customer Support Tickets
CREATE TABLE IF NOT EXISTS RAW_SUPPORT_TICKETS (
    TICKET_ID           STRING,
    CUSTOMER_ID         STRING,
    CATEGORY            STRING,
    PRIORITY            STRING,
    CHANNEL             STRING,
    CREATED_AT          TIMESTAMP_NTZ,
    RESOLVED_AT         TIMESTAMP_NTZ,
    RESOLUTION_TIME_HOURS NUMBER(10,1),
    STATUS              STRING,
    SATISFACTION_SCORE  NUMBER(2,0),
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 1.8 Network Tower Outages
CREATE TABLE IF NOT EXISTS RAW_NETWORK_OUTAGES (
    OUTAGE_ID           STRING,
    TOWER_ID            STRING,
    OUTAGE_START        TIMESTAMP_NTZ,
    OUTAGE_END          TIMESTAMP_NTZ,
    DURATION_MINUTES    NUMBER(10,0),
    SEVERITY            STRING,
    CAUSE               STRING,
    ESTIMATED_IMPACTED_USERS NUMBER(10,0),
    LOAD_DATE           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ------------------------------------------------------------------------------
-- 2. COPY INTO STATEMENTS (LOAD FROM @CRM_STAGE)
-- ------------------------------------------------------------------------------

COPY INTO RAW_CUSTOMERS (
    CUSTOMER_ID, GENDER, SENIOR_CITIZEN, PARTNER, DEPENDENTS, TENURE,
    PHONE_SERVICE, MULTIPLE_LINES, INTERNET_SERVICE, ONLINE_SECURITY,
    ONLINE_BACKUP, DEVICE_PROTECTION, TECH_SUPPORT, STREAMING_TV,
    STREAMING_MOVIES, CONTRACT, PAPERLESS_BILLING, PAYMENT_METHOD,
    MONTHLY_CHARGES, TOTAL_CHARGES, CHURN
)
FROM @CRM_STAGE/customer_churn.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_PLANS (
    PLAN_ID, PLAN_NAME, MONTHLY_PRICE, DATA_LIMIT_GB,
    NETWORK_TYPE, VOICE_MINUTES, SMS_LIMIT, VALIDITY_DAYS, PLAN_CATEGORY
)
FROM @CRM_STAGE/plans.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_TOWERS (
    TOWER_ID, TOWER_NAME, CITY, STATE, LATITUDE, LONGITUDE,
    TECHNOLOGY, VENDOR, CAPACITY, INSTALLATION_DATE, STATUS
)
FROM @CRM_STAGE/towers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_BILLING (
    BILL_ID, CUSTOMER_ID, BILLING_PERIOD, BILL_DATE, DUE_DATE,
    BASE_AMOUNT, ADDITIONAL_CHARGES, DISCOUNT_AMOUNT, TAX_AMOUNT,
    TOTAL_AMOUNT, PAYMENT_STATUS
)
FROM @CRM_STAGE/customer_billing.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_PAYMENTS (
    PAYMENT_ID, BILL_ID, CUSTOMER_ID, PAYMENT_DATETIME, AMOUNT,
    PAYMENT_METHOD, PAYMENT_GATEWAY, TRANSACTION_STATUS, TRANSACTION_REF
)
FROM @CRM_STAGE/customer_payments.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_USAGE (
    USAGE_ID, CUSTOMER_ID, USAGE_DATE, TOWER_ID, VOICE_MINUTES,
    DATA_USAGE_MB, DATA_USAGE_GB, SMS_COUNT, IS_ROAMING
)
FROM @CRM_STAGE/daily_usage.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_SUPPORT_TICKETS (
    TICKET_ID, CUSTOMER_ID, CATEGORY, PRIORITY, CHANNEL,
    CREATED_AT, RESOLVED_AT, RESOLUTION_TIME_HOURS, STATUS, SATISFACTION_SCORE
)
FROM @CRM_STAGE/support_tickets.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RAW_NETWORK_OUTAGES (
    OUTAGE_ID, TOWER_ID, OUTAGE_START, OUTAGE_END,
    DURATION_MINUTES, SEVERITY, CAUSE, ESTIMATED_IMPACTED_USERS
)
FROM @CRM_STAGE/tower_outages.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- ------------------------------------------------------------------------------
-- 3. VERIFY ROW COUNTS IN RAW LAYER
-- ------------------------------------------------------------------------------
SELECT 'RAW_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROWS FROM RAW_CUSTOMERS
UNION ALL SELECT 'RAW_PLANS', COUNT(*) FROM RAW_PLANS
UNION ALL SELECT 'RAW_TOWERS', COUNT(*) FROM RAW_TOWERS
UNION ALL SELECT 'RAW_BILLING', COUNT(*) FROM RAW_BILLING
UNION ALL SELECT 'RAW_PAYMENTS', COUNT(*) FROM RAW_PAYMENTS
UNION ALL SELECT 'RAW_USAGE', COUNT(*) FROM RAW_USAGE
UNION ALL SELECT 'RAW_SUPPORT_TICKETS', COUNT(*) FROM RAW_SUPPORT_TICKETS
UNION ALL SELECT 'RAW_NETWORK_OUTAGES', COUNT(*) FROM RAW_NETWORK_OUTAGES
ORDER BY TABLE_NAME;
