-- ==============================================================================
-- TELECOM DATA PLATFORM — SNOWFLAKE INFRASTRUCTURE SETUP
-- SCRIPT 04: STAGING Layer Views (Silver Layer Transformations)
-- ==============================================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;
USE SCHEMA STAGING;

-- ------------------------------------------------------------------------------
-- 1. STG_CUSTOMERS (Demographics, Services, Contract)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_CUSTOMERS AS
SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    UPPER(TRIM(GENDER)) AS GENDER,
    CAST(SENIOR_CITIZEN AS NUMBER(1,0)) AS SENIOR_CITIZEN,
    CASE WHEN TRIM(PARTNER) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PARTNER,
    CASE WHEN TRIM(DEPENDENTS) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_DEPENDENTS,
    CAST(TENURE AS NUMBER(5,0)) AS TENURE_MONTHS,
    CASE WHEN TRIM(PHONE_SERVICE) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PHONE_SERVICE,
    TRIM(MULTIPLE_LINES) AS MULTIPLE_LINES,
    TRIM(INTERNET_SERVICE) AS INTERNET_SERVICE,
    TRIM(ONLINE_SECURITY) AS ONLINE_SECURITY,
    TRIM(ONLINE_BACKUP) AS ONLINE_BACKUP,
    TRIM(DEVICE_PROTECTION) AS DEVICE_PROTECTION,
    TRIM(TECH_SUPPORT) AS TECH_SUPPORT,
    TRIM(STREAMING_TV) AS STREAMING_TV,
    TRIM(STREAMING_MOVIES) AS STREAMING_MOVIES,
    TRIM(CONTRACT) AS CONTRACT,
    CASE WHEN TRIM(PAPERLESS_BILLING) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PAPERLESS_BILLING,
    TRIM(PAYMENT_METHOD) AS PAYMENT_METHOD,
    CAST(NULLIF(TRIM(MONTHLY_CHARGES), '') AS NUMBER(12,2)) AS MONTHLY_CHARGES,
    CAST(NULLIF(TRIM(TOTAL_CHARGES), '') AS NUMBER(12,2)) AS TOTAL_CHARGES,
    TRIM(CHURN) AS CHURN,
    CASE WHEN TRIM(CHURN) = 'Yes' THEN 1 ELSE 0 END AS CHURN_FLAG,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_CUSTOMERS;

-- ------------------------------------------------------------------------------
-- 2. STG_PLANS (Catalog, Pricing, Allowances)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_PLANS AS
SELECT
    TRIM(PLAN_ID) AS PLAN_ID,
    TRIM(PLAN_NAME) AS PLAN_NAME,
    CAST(MONTHLY_PRICE AS NUMBER(10,2)) AS MONTHLY_PRICE,
    CAST(DATA_LIMIT_GB AS NUMBER(10,0)) AS DATA_LIMIT_GB,
    CASE WHEN DATA_LIMIT_GB = -1 THEN TRUE ELSE FALSE END AS IS_UNLIMITED_DATA,
    TRIM(NETWORK_TYPE) AS NETWORK_TYPE,
    CAST(VOICE_MINUTES AS NUMBER(10,0)) AS VOICE_MINUTES,
    CASE WHEN VOICE_MINUTES = -1 THEN TRUE ELSE FALSE END AS IS_UNLIMITED_VOICE,
    CAST(SMS_LIMIT AS NUMBER(10,0)) AS SMS_LIMIT,
    CAST(VALIDITY_DAYS AS NUMBER(5,0)) AS VALIDITY_DAYS,
    TRIM(PLAN_CATEGORY) AS PLAN_CATEGORY,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_PLANS;

-- ------------------------------------------------------------------------------
-- 3. STG_TOWERS (Radio Access Network Cell Towers)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_TOWERS AS
SELECT
    TRIM(TOWER_ID) AS TOWER_ID,
    TRIM(TOWER_NAME) AS TOWER_NAME,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    CAST(LATITUDE AS NUMBER(10,6)) AS LATITUDE,
    CAST(LONGITUDE AS NUMBER(10,6)) AS LONGITUDE,
    TRIM(TECHNOLOGY) AS TECHNOLOGY,
    TRIM(VENDOR) AS VENDOR,
    CAST(CAPACITY AS NUMBER(10,0)) AS CAPACITY,
    CAST(INSTALLATION_DATE AS DATE) AS INSTALLATION_DATE,
    TRIM(STATUS) AS STATUS,
    CASE WHEN TRIM(STATUS) = 'Active' THEN TRUE ELSE FALSE END AS IS_ACTIVE,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_TOWERS;

-- ------------------------------------------------------------------------------
-- 4. STG_BILLING (Monthly Customer Statements)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_BILLING AS
SELECT
    TRIM(BILL_ID) AS BILL_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(BILLING_PERIOD) AS BILLING_PERIOD,
    CAST(BILL_DATE AS DATE) AS BILL_DATE,
    CAST(DUE_DATE AS DATE) AS DUE_DATE,
    CAST(BASE_AMOUNT AS NUMBER(10,2)) AS BASE_AMOUNT,
    CAST(ADDITIONAL_CHARGES AS NUMBER(10,2)) AS ADDITIONAL_CHARGES,
    CAST(DISCOUNT_AMOUNT AS NUMBER(10,2)) AS DISCOUNT_AMOUNT,
    CAST(TAX_AMOUNT AS NUMBER(10,2)) AS TAX_AMOUNT,
    CAST(TOTAL_AMOUNT AS NUMBER(10,2)) AS TOTAL_AMOUNT,
    UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
    CASE WHEN UPPER(TRIM(PAYMENT_STATUS)) = 'PAID' THEN TRUE ELSE FALSE END AS IS_PAID,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_BILLING;

-- ------------------------------------------------------------------------------
-- 5. STG_PAYMENTS (Fulfillment & Payment Gateways)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_PAYMENTS AS
SELECT
    TRIM(PAYMENT_ID) AS PAYMENT_ID,
    TRIM(BILL_ID) AS BILL_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    CAST(PAYMENT_DATETIME AS TIMESTAMP_NTZ) AS PAYMENT_DATETIME,
    CAST(PAYMENT_DATETIME AS DATE) AS PAYMENT_DATE,
    CAST(AMOUNT AS NUMBER(10,2)) AS AMOUNT,
    TRIM(PAYMENT_METHOD) AS PAYMENT_METHOD,
    TRIM(PAYMENT_GATEWAY) AS PAYMENT_GATEWAY,
    UPPER(TRIM(TRANSACTION_STATUS)) AS TRANSACTION_STATUS,
    CASE WHEN UPPER(TRIM(TRANSACTION_STATUS)) = 'SUCCESS' THEN TRUE ELSE FALSE END AS IS_SUCCESSFUL,
    TRIM(TRANSACTION_REF) AS TRANSACTION_REF,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_PAYMENTS;

-- ------------------------------------------------------------------------------
-- 6. STG_USAGE (Daily Subscriber Usage Metrics)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_USAGE AS
SELECT
    TRIM(USAGE_ID) AS USAGE_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    CAST(USAGE_DATE AS DATE) AS USAGE_DATE,
    TRIM(TOWER_ID) AS TOWER_ID,
    CAST(VOICE_MINUTES AS NUMBER(10,0)) AS VOICE_MINUTES,
    CAST(DATA_USAGE_MB AS NUMBER(12,2)) AS DATA_USAGE_MB,
    CAST(DATA_USAGE_GB AS NUMBER(12,3)) AS DATA_USAGE_GB,
    CAST(SMS_COUNT AS NUMBER(10,0)) AS SMS_COUNT,
    COALESCE(IS_ROAMING, FALSE) AS IS_ROAMING,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_USAGE;

-- ------------------------------------------------------------------------------
-- 7. STG_SUPPORT_TICKETS (Service Desk & Turnaround)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_SUPPORT_TICKETS AS
SELECT
    TRIM(TICKET_ID) AS TICKET_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(CATEGORY) AS CATEGORY,
    TRIM(PRIORITY) AS PRIORITY,
    TRIM(CHANNEL) AS CHANNEL,
    CAST(CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    CAST(RESOLVED_AT AS TIMESTAMP_NTZ) AS RESOLVED_AT,
    CAST(RESOLUTION_TIME_HOURS AS NUMBER(10,1)) AS RESOLUTION_TIME_HOURS,
    UPPER(TRIM(STATUS)) AS STATUS,
    CASE WHEN UPPER(TRIM(STATUS)) IN ('RESOLVED', 'CLOSED') THEN TRUE ELSE FALSE END AS IS_RESOLVED,
    CAST(SATISFACTION_SCORE AS NUMBER(2,0)) AS SATISFACTION_SCORE,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_SUPPORT_TICKETS;

-- ------------------------------------------------------------------------------
-- 8. STG_NETWORK_OUTAGES (Tower Incidents & Downtime)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW STG_NETWORK_OUTAGES AS
SELECT
    TRIM(OUTAGE_ID) AS OUTAGE_ID,
    TRIM(TOWER_ID) AS TOWER_ID,
    CAST(OUTAGE_START AS TIMESTAMP_NTZ) AS OUTAGE_START,
    CAST(OUTAGE_END AS TIMESTAMP_NTZ) AS OUTAGE_END,
    CAST(DURATION_MINUTES AS NUMBER(10,0)) AS DURATION_MINUTES,
    TRIM(SEVERITY) AS SEVERITY,
    TRIM(CAUSE) AS CAUSE,
    CAST(ESTIMATED_IMPACTED_USERS AS NUMBER(10,0)) AS ESTIMATED_IMPACTED_USERS,
    LOAD_DATE
FROM TELECOM_DB.RAW.RAW_NETWORK_OUTAGES;

-- ------------------------------------------------------------------------------
-- 9. VERIFY VIEWS IN STAGING LAYER
-- ------------------------------------------------------------------------------
SHOW VIEWS IN SCHEMA TELECOM_DB.STAGING;
