-- ==============================================================================
-- TELECOM DATA PLATFORM — SNOWFLAKE INFRASTRUCTURE SETUP
-- SCRIPT 06: Analytics Marts & Predictive Churn Risk Scoring
-- ==============================================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;
USE SCHEMA MARTS;

-- ------------------------------------------------------------------------------
-- 1. CHURN_RISK_ANALYSIS (Predictive Multi-Factor Scoring Mart)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE TABLE CHURN_RISK_ANALYSIS AS
WITH billing AS (
    SELECT
        CUSTOMER_ID,
        SUM(CASE WHEN PAYMENT_STATUS = 'OVERDUE' THEN 1 ELSE 0 END) AS OVERDUE_BILLS_COUNT,
        AVG(DAYS_TO_PAY) AS AVG_PAYMENT_DELAY_DAYS
    FROM TELECOM_DB.MARTS.FCT_BILLING_PAYMENTS
    GROUP BY CUSTOMER_ID
)
SELECT
    c.CUSTOMER_ID,
    c.GENDER,
    c.SENIOR_CITIZEN,
    c.TENURE_MONTHS,
    c.TENURE_COHORT,
    c.CONTRACT,
    c.PAYMENT_METHOD,
    c.MONTHLY_CHARGES,
    c.TOTAL_CHARGES,
    c.ACTIVE_SERVICES_COUNT,
    c.TOTAL_SUPPORT_TICKETS,
    c.AVG_CSAT_SCORE,
    COALESCE(b.OVERDUE_BILLS_COUNT, 0) AS OVERDUE_BILLS_COUNT,
    ROUND(COALESCE(b.AVG_PAYMENT_DELAY_DAYS, 0), 1) AS AVG_PAYMENT_DELAY_DAYS,
    c.CHURN_FLAG,

    -- Multi-factor churn risk scoring (0 to 100 points)
    (
        (CASE WHEN c.CONTRACT = 'Month-to-month' THEN 35 WHEN c.CONTRACT = 'One year' THEN 15 ELSE 5 END) +
        (CASE WHEN c.TENURE_MONTHS <= 6 THEN 25 WHEN c.TENURE_MONTHS <= 12 THEN 15 WHEN c.TENURE_MONTHS <= 24 THEN 8 ELSE 0 END) +
        (CASE WHEN c.TOTAL_SUPPORT_TICKETS >= 3 THEN 20 WHEN c.TOTAL_SUPPORT_TICKETS >= 1 THEN 10 ELSE 0 END) +
        (CASE WHEN c.AVG_CSAT_SCORE <= 2.0 THEN 15 WHEN c.AVG_CSAT_SCORE <= 3.0 THEN 8 ELSE 0 END) +
        (CASE WHEN COALESCE(b.OVERDUE_BILLS_COUNT, 0) > 0 THEN 15 ELSE 0 END)
    ) AS CHURN_RISK_SCORE,

    CASE
        WHEN (
            (CASE WHEN c.CONTRACT = 'Month-to-month' THEN 35 WHEN c.CONTRACT = 'One year' THEN 15 ELSE 5 END) +
            (CASE WHEN c.TENURE_MONTHS <= 6 THEN 25 WHEN c.TENURE_MONTHS <= 12 THEN 15 WHEN c.TENURE_MONTHS <= 24 THEN 8 ELSE 0 END) +
            (CASE WHEN c.TOTAL_SUPPORT_TICKETS >= 3 THEN 20 WHEN c.TOTAL_SUPPORT_TICKETS >= 1 THEN 10 ELSE 0 END) +
            (CASE WHEN c.AVG_CSAT_SCORE <= 2.0 THEN 15 WHEN c.AVG_CSAT_SCORE <= 3.0 THEN 8 ELSE 0 END) +
            (CASE WHEN COALESCE(b.OVERDUE_BILLS_COUNT, 0) > 0 THEN 15 ELSE 0 END)
        ) >= 65 THEN 'HIGH RISK'
        WHEN (
            (CASE WHEN c.CONTRACT = 'Month-to-month' THEN 35 WHEN c.CONTRACT = 'One year' THEN 15 ELSE 5 END) +
            (CASE WHEN c.TENURE_MONTHS <= 6 THEN 25 WHEN c.TENURE_MONTHS <= 12 THEN 15 WHEN c.TENURE_MONTHS <= 24 THEN 8 ELSE 0 END) +
            (CASE WHEN c.TOTAL_SUPPORT_TICKETS >= 3 THEN 20 WHEN c.TOTAL_SUPPORT_TICKETS >= 1 THEN 10 ELSE 0 END) +
            (CASE WHEN c.AVG_CSAT_SCORE <= 2.0 THEN 15 WHEN c.AVG_CSAT_SCORE <= 3.0 THEN 8 ELSE 0 END) +
            (CASE WHEN COALESCE(b.OVERDUE_BILLS_COUNT, 0) > 0 THEN 15 ELSE 0 END)
        ) >= 35 THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END AS CHURN_RISK_TIER,

    c.LOAD_DATE
FROM TELECOM_DB.MARTS.DIM_CUSTOMERS c
LEFT JOIN billing b
    ON c.CUSTOMER_ID = b.CUSTOMER_ID;

-- ------------------------------------------------------------------------------
-- 2. CHURN_BY_CONTRACT (Aggregated Churn by Contract Term)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE TABLE CHURN_BY_CONTRACT AS
SELECT
    CONTRACT,
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(CHURN_FLAG) AS CHURNED_CUSTOMERS,
    COUNT(*) - SUM(CHURN_FLAG) AS ACTIVE_CUSTOMERS,
    ROUND(SUM(CHURN_FLAG) * 100.0 / COUNT(*), 2) AS CHURN_RATE_PERCENT
FROM TELECOM_DB.MARTS.DIM_CUSTOMERS
GROUP BY CONTRACT
ORDER BY CHURN_RATE_PERCENT DESC;

-- ------------------------------------------------------------------------------
-- 3. CUSTOMER_CHURN_SUMMARY (Executive KPI Summary)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE TABLE CUSTOMER_CHURN_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(CHURN_FLAG) AS CHURNED_CUSTOMERS,
    COUNT(*) - SUM(CHURN_FLAG) AS ACTIVE_CUSTOMERS,
    ROUND(SUM(CHURN_FLAG) * 100.0 / COUNT(*), 2) AS CHURN_RATE_PERCENT
FROM TELECOM_DB.MARTS.DIM_CUSTOMERS;

-- ------------------------------------------------------------------------------
-- 4. NETWORK_PERFORMANCE_MARTS (Cell Tower Load & Reliability Mart)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE TABLE NETWORK_PERFORMANCE_MARTS AS
WITH usage_summary AS (
    SELECT
        TOWER_ID,
        COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_SUBSCRIBERS,
        SUM(DATA_USAGE_GB) AS TOTAL_DATA_SERVED_GB,
        SUM(VOICE_MINUTES) AS TOTAL_VOICE_MINUTES,
        AVG(DATA_USAGE_GB) AS AVG_DATA_PER_EVENT_GB
    FROM TELECOM_DB.MARTS.FCT_DAILY_USAGE
    GROUP BY TOWER_ID
)
SELECT
    t.TOWER_KEY,
    t.TOWER_ID,
    t.TOWER_NAME,
    t.CITY,
    t.STATE,
    t.TECHNOLOGY,
    t.VENDOR,
    t.CAPACITY,
    t.STATUS,
    t.IS_ACTIVE,
    t.LIFETIME_OUTAGES_COUNT,
    t.TOTAL_DOWNTIME_MINUTES,
    t.TOTAL_SUBSCRIBERS_IMPACTED,
    t.UPTIME_AVAILABILITY_PCT,
    COALESCE(u.DISTINCT_SUBSCRIBERS, 0) AS RECENT_ACTIVE_USERS,
    ROUND(COALESCE(u.TOTAL_DATA_SERVED_GB, 0), 2) AS TOTAL_DATA_SERVED_GB,
    COALESCE(u.TOTAL_VOICE_MINUTES, 0) AS TOTAL_VOICE_MINUTES,
    ROUND(
        (COALESCE(u.DISTINCT_SUBSCRIBERS, 0) * 100.0 / NULLIF(t.CAPACITY, 0)),
        2
    ) AS CAPACITY_UTILIZATION_PCT,
    CURRENT_TIMESTAMP() AS MART_REFRESH_TIMESTAMP
FROM TELECOM_DB.MARTS.DIM_TOWERS t
LEFT JOIN usage_summary u
    ON t.TOWER_ID = u.TOWER_ID;
