-- ==============================================================================
-- TELECOM DATA PLATFORM — SNOWFLAKE INFRASTRUCTURE SETUP
-- SCRIPT 08: Data Validation, Reconciliations & Quality Audits
-- ==============================================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;

-- ------------------------------------------------------------------------------
-- 1. CROSS-LAYER ROW COUNT RECONCILIATION
-- ------------------------------------------------------------------------------
SELECT '1. RAW' AS LAYER, 'RAW_CUSTOMERS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM TELECOM_DB.RAW.RAW_CUSTOMERS
UNION ALL SELECT '1. RAW', 'RAW_BILLING', COUNT(*) FROM TELECOM_DB.RAW.RAW_BILLING
UNION ALL SELECT '1. RAW', 'RAW_PAYMENTS', COUNT(*) FROM TELECOM_DB.RAW.RAW_PAYMENTS
UNION ALL SELECT '1. RAW', 'RAW_USAGE', COUNT(*) FROM TELECOM_DB.RAW.RAW_USAGE
UNION ALL SELECT '1. RAW', 'RAW_SUPPORT_TICKETS', COUNT(*) FROM TELECOM_DB.RAW.RAW_SUPPORT_TICKETS
UNION ALL SELECT '1. RAW', 'RAW_NETWORK_OUTAGES', COUNT(*) FROM TELECOM_DB.RAW.RAW_NETWORK_OUTAGES
UNION ALL SELECT '1. RAW', 'RAW_TOWERS', COUNT(*) FROM TELECOM_DB.RAW.RAW_TOWERS
UNION ALL SELECT '1. RAW', 'RAW_PLANS', COUNT(*) FROM TELECOM_DB.RAW.RAW_PLANS
UNION ALL SELECT '2. STAGING', 'STG_CUSTOMERS', COUNT(*) FROM TELECOM_DB.STAGING.STG_CUSTOMERS
UNION ALL SELECT '2. STAGING', 'STG_BILLING', COUNT(*) FROM TELECOM_DB.STAGING.STG_BILLING
UNION ALL SELECT '2. STAGING', 'STG_PAYMENTS', COUNT(*) FROM TELECOM_DB.STAGING.STG_PAYMENTS
UNION ALL SELECT '2. STAGING', 'STG_USAGE', COUNT(*) FROM TELECOM_DB.STAGING.STG_USAGE
UNION ALL SELECT '2. STAGING', 'STG_SUPPORT_TICKETS', COUNT(*) FROM TELECOM_DB.STAGING.STG_SUPPORT_TICKETS
UNION ALL SELECT '2. STAGING', 'STG_NETWORK_OUTAGES', COUNT(*) FROM TELECOM_DB.STAGING.STG_NETWORK_OUTAGES
UNION ALL SELECT '2. STAGING', 'STG_TOWERS', COUNT(*) FROM TELECOM_DB.STAGING.STG_TOWERS
UNION ALL SELECT '2. STAGING', 'STG_PLANS', COUNT(*) FROM TELECOM_DB.STAGING.STG_PLANS
UNION ALL SELECT '3. MARTS', 'DIM_CUSTOMERS', COUNT(*) FROM TELECOM_DB.MARTS.DIM_CUSTOMERS
UNION ALL SELECT '3. MARTS', 'DIM_PLANS', COUNT(*) FROM TELECOM_DB.MARTS.DIM_PLANS
UNION ALL SELECT '3. MARTS', 'DIM_TOWERS', COUNT(*) FROM TELECOM_DB.MARTS.DIM_TOWERS
UNION ALL SELECT '3. MARTS', 'FCT_BILLING_PAYMENTS', COUNT(*) FROM TELECOM_DB.MARTS.FCT_BILLING_PAYMENTS
UNION ALL SELECT '3. MARTS', 'FCT_DAILY_USAGE', COUNT(*) FROM TELECOM_DB.MARTS.FCT_DAILY_USAGE
UNION ALL SELECT '3. MARTS', 'FCT_SUPPORT_TICKETS', COUNT(*) FROM TELECOM_DB.MARTS.FCT_SUPPORT_TICKETS
UNION ALL SELECT '3. MARTS', 'CHURN_RISK_ANALYSIS', COUNT(*) FROM TELECOM_DB.MARTS.CHURN_RISK_ANALYSIS
UNION ALL SELECT '3. MARTS', 'NETWORK_PERFORMANCE_MARTS', COUNT(*) FROM TELECOM_DB.MARTS.NETWORK_PERFORMANCE_MARTS
ORDER BY LAYER, OBJECT_NAME;

-- ------------------------------------------------------------------------------
-- 2. PRIMARY KEY UNIQUENESS AUDIT (MUST RETURN 0 DUPLICATES)
-- ------------------------------------------------------------------------------
SELECT 'DIM_CUSTOMERS DUPLICATES' AS AUDIT_TEST, COUNT(*) - COUNT(DISTINCT CUSTOMER_KEY) AS VIOLATIONS FROM TELECOM_DB.MARTS.DIM_CUSTOMERS
UNION ALL SELECT 'DIM_PLANS DUPLICATES', COUNT(*) - COUNT(DISTINCT PLAN_KEY) FROM TELECOM_DB.MARTS.DIM_PLANS
UNION ALL SELECT 'DIM_TOWERS DUPLICATES', COUNT(*) - COUNT(DISTINCT TOWER_KEY) FROM TELECOM_DB.MARTS.DIM_TOWERS
UNION ALL SELECT 'FCT_BILLING_PAYMENTS DUPLICATES', COUNT(*) - COUNT(DISTINCT BILLING_KEY) FROM TELECOM_DB.MARTS.FCT_BILLING_PAYMENTS
UNION ALL SELECT 'FCT_DAILY_USAGE DUPLICATES', COUNT(*) - COUNT(DISTINCT USAGE_KEY) FROM TELECOM_DB.MARTS.FCT_DAILY_USAGE
UNION ALL SELECT 'FCT_SUPPORT_TICKETS DUPLICATES', COUNT(*) - COUNT(DISTINCT TICKET_KEY) FROM TELECOM_DB.MARTS.FCT_SUPPORT_TICKETS;

-- ------------------------------------------------------------------------------
-- 3. CRITICAL NULL CHECK AUDIT (MUST RETURN 0 FAILURES)
-- ------------------------------------------------------------------------------
SELECT 'NULL CUSTOMER_KEY IN DIM_CUSTOMERS' AS AUDIT_TEST, COUNT(*) AS FAILURES FROM TELECOM_DB.MARTS.DIM_CUSTOMERS WHERE CUSTOMER_KEY IS NULL
UNION ALL SELECT 'NULL CHURN_FLAG IN DIM_CUSTOMERS', COUNT(*) FROM TELECOM_DB.MARTS.DIM_CUSTOMERS WHERE CHURN_FLAG IS NULL
UNION ALL SELECT 'NULL BILL_ID IN FCT_BILLING_PAYMENTS', COUNT(*) FROM TELECOM_DB.MARTS.FCT_BILLING_PAYMENTS WHERE BILL_ID IS NULL
UNION ALL SELECT 'NULL USAGE_ID IN FCT_DAILY_USAGE', COUNT(*) FROM TELECOM_DB.MARTS.FCT_DAILY_USAGE WHERE USAGE_ID IS NULL
UNION ALL SELECT 'NULL TICKET_ID IN FCT_SUPPORT_TICKETS', COUNT(*) FROM TELECOM_DB.MARTS.FCT_SUPPORT_TICKETS WHERE TICKET_ID IS NULL;

-- ------------------------------------------------------------------------------
-- 4. REFERENTIAL INTEGRITY ORPHAN CHECKS
-- ------------------------------------------------------------------------------
-- Check if any billing record exists for an unknown customer:
SELECT 
    COUNT(*) AS ORPHAN_BILLING_RECORDS
FROM TELECOM_DB.MARTS.FCT_BILLING_PAYMENTS b
LEFT JOIN TELECOM_DB.MARTS.DIM_CUSTOMERS c
    ON b.CUSTOMER_KEY = c.CUSTOMER_KEY
WHERE c.CUSTOMER_KEY IS NULL;

-- Check if any usage record links to an unknown cell tower:
SELECT 
    COUNT(*) AS ORPHAN_USAGE_TOWERS
FROM TELECOM_DB.MARTS.FCT_DAILY_USAGE u
LEFT JOIN TELECOM_DB.MARTS.DIM_TOWERS t
    ON u.TOWER_KEY = t.TOWER_KEY
WHERE t.TOWER_KEY IS NULL;
