version: 2

models:
  - name: stg_customers
    description: "Cleaned and standardized customer data from the raw layer."

    columns:
      - name: CUSTOMER_ID
        description: "Unique identifier for each customer."
        data_tests:
          - not_null
          - unique

      - name: MONTHLY_CHARGES
        description: "Customer's monthly charge."
        data_tests:
          - not_null