version: 2

sources:
  - name: raw
    database: TELECOM_DB
    schema: RAW

    tables:
      - name: raw_customers
        columns:
          - name: CUSTOMER_ID
            data_tests:
              - not_null
              - unique