{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_usage') }}
)

SELECT
    TRIM(USAGE_ID) AS USAGE_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    CAST(USAGE_DATE AS DATE) AS USAGE_DATE,
    TRIM(TOWER_ID) AS TOWER_ID,
    CAST(VOICE_MINUTES AS NUMBER(10,0)) AS VOICE_MINUTES,
    CAST(DATA_USAGE_MB AS NUMBER(12,2)) AS DATA_USAGE_MB,
    CAST(DATA_USAGE_GB AS NUMBER(12,3)) AS DATA_USAGE_GB,
    CAST(SMS_COUNT AS NUMBER(10,0)) AS SMS_COUNT,
    COALESCE(IS_ROAMING, FALSE) AS IS_ROAMING,
    LOAD_DATE
FROM source
