{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_plans') }}
)

SELECT
    TRIM(PLAN_ID) AS PLAN_ID,
    TRIM(PLAN_NAME) AS PLAN_NAME,
    CAST(MONTHLY_PRICE AS NUMBER(10,2)) AS MONTHLY_PRICE,
    CAST(DATA_LIMIT_GB AS NUMBER(10,0)) AS DATA_LIMIT_GB,
    CASE WHEN DATA_LIMIT_GB = -1 THEN TRUE ELSE FALSE END AS IS_UNLIMITED_DATA,
    TRIM(NETWORK_TYPE) AS NETWORK_TYPE,
    CAST(VOICE_MINUTES AS NUMBER(10,0)) AS VOICE_MINUTES,
    CASE WHEN VOICE_MINUTES = -1 THEN TRUE ELSE FALSE END AS IS_UNLIMITED_VOICE,
    CAST(SMS_LIMIT AS NUMBER(10,0)) AS SMS_LIMIT,
    CAST(VALIDITY_DAYS AS NUMBER(5,0)) AS VALIDITY_DAYS,
    TRIM(PLAN_CATEGORY) AS PLAN_CATEGORY,
    LOAD_DATE
FROM source
