{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_towers') }}
)

SELECT
    TRIM(TOWER_ID) AS TOWER_ID,
    TRIM(TOWER_NAME) AS TOWER_NAME,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    CAST(LATITUDE AS NUMBER(10,6)) AS LATITUDE,
    CAST(LONGITUDE AS NUMBER(10,6)) AS LONGITUDE,
    TRIM(TECHNOLOGY) AS TECHNOLOGY,
    TRIM(VENDOR) AS VENDOR,
    CAST(CAPACITY AS NUMBER(10,0)) AS CAPACITY,
    CAST(INSTALLATION_DATE AS DATE) AS INSTALLATION_DATE,
    TRIM(STATUS) AS STATUS,
    CASE WHEN TRIM(STATUS) = 'Active' THEN TRUE ELSE FALSE END AS IS_ACTIVE,
    LOAD_DATE
FROM source
