{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_billing') }}
)

SELECT
    TRIM(BILL_ID) AS BILL_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(BILLING_PERIOD) AS BILLING_PERIOD,
    CAST(BILL_DATE AS DATE) AS BILL_DATE,
    CAST(DUE_DATE AS DATE) AS DUE_DATE,
    CAST(BASE_AMOUNT AS NUMBER(10,2)) AS BASE_AMOUNT,
    CAST(ADDITIONAL_CHARGES AS NUMBER(10,2)) AS ADDITIONAL_CHARGES,
    CAST(DISCOUNT_AMOUNT AS NUMBER(10,2)) AS DISCOUNT_AMOUNT,
    CAST(TAX_AMOUNT AS NUMBER(10,2)) AS TAX_AMOUNT,
    CAST(TOTAL_AMOUNT AS NUMBER(10,2)) AS TOTAL_AMOUNT,
    UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
    CASE WHEN UPPER(TRIM(PAYMENT_STATUS)) = 'PAID' THEN TRUE ELSE FALSE END AS IS_PAID,
    LOAD_DATE
FROM source
