{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_customers') }}
)

SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    UPPER(TRIM(GENDER)) AS GENDER,
    CAST(SENIOR_CITIZEN AS NUMBER(1,0)) AS SENIOR_CITIZEN,
    CASE WHEN TRIM(PARTNER) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PARTNER,
    CASE WHEN TRIM(DEPENDENTS) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_DEPENDENTS,
    CAST(TENURE AS NUMBER(5,0)) AS TENURE_MONTHS,
    CASE WHEN TRIM(PHONE_SERVICE) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PHONE_SERVICE,
    TRIM(MULTIPLE_LINES) AS MULTIPLE_LINES,
    TRIM(INTERNET_SERVICE) AS INTERNET_SERVICE,
    TRIM(ONLINE_SECURITY) AS ONLINE_SECURITY,
    TRIM(ONLINE_BACKUP) AS ONLINE_BACKUP,
    TRIM(DEVICE_PROTECTION) AS DEVICE_PROTECTION,
    TRIM(TECH_SUPPORT) AS TECH_SUPPORT,
    TRIM(STREAMING_TV) AS STREAMING_TV,
    TRIM(STREAMING_MOVIES) AS STREAMING_MOVIES,
    TRIM(CONTRACT) AS CONTRACT,
    CASE WHEN TRIM(PAPERLESS_BILLING) = 'Yes' THEN TRUE ELSE FALSE END AS HAS_PAPERLESS_BILLING,
    TRIM(PAYMENT_METHOD) AS PAYMENT_METHOD,
    CAST(NULLIF(TRIM(MONTHLY_CHARGES), '') AS NUMBER(12,2)) AS MONTHLY_CHARGES,
    CAST(NULLIF(TRIM(TOTAL_CHARGES), '') AS NUMBER(12,2)) AS TOTAL_CHARGES,
    TRIM(CHURN) AS CHURN,
    CASE WHEN TRIM(CHURN) = 'Yes' THEN 1 ELSE 0 END AS CHURN_FLAG,
    LOAD_DATE
FROM source