{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_payments') }}
)

SELECT
    TRIM(PAYMENT_ID) AS PAYMENT_ID,
    TRIM(BILL_ID) AS BILL_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    CAST(PAYMENT_DATETIME AS TIMESTAMP_NTZ) AS PAYMENT_DATETIME,
    CAST(PAYMENT_DATETIME AS DATE) AS PAYMENT_DATE,
    CAST(AMOUNT AS NUMBER(10,2)) AS AMOUNT,
    TRIM(PAYMENT_METHOD) AS PAYMENT_METHOD,
    TRIM(PAYMENT_GATEWAY) AS PAYMENT_GATEWAY,
    UPPER(TRIM(TRANSACTION_STATUS)) AS TRANSACTION_STATUS,
    CASE WHEN UPPER(TRIM(TRANSACTION_STATUS)) = 'SUCCESS' THEN TRUE ELSE FALSE END AS IS_SUCCESSFUL,
    TRIM(TRANSACTION_REF) AS TRANSACTION_REF,
    LOAD_DATE
FROM source
