{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_support_tickets') }}
)

SELECT
    TRIM(TICKET_ID) AS TICKET_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(CATEGORY) AS CATEGORY,
    TRIM(PRIORITY) AS PRIORITY,
    TRIM(CHANNEL) AS CHANNEL,
    CAST(CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    CAST(RESOLVED_AT AS TIMESTAMP_NTZ) AS RESOLVED_AT,
    CAST(RESOLUTION_TIME_HOURS AS NUMBER(10,1)) AS RESOLUTION_TIME_HOURS,
    UPPER(TRIM(STATUS)) AS STATUS,
    CASE WHEN UPPER(TRIM(STATUS)) IN ('RESOLVED', 'CLOSED') THEN TRUE ELSE FALSE END AS IS_RESOLVED,
    CAST(SATISFACTION_SCORE AS NUMBER(2,0)) AS SATISFACTION_SCORE,
    LOAD_DATE
FROM source
