{{ config(
    materialized='view'
) }}

SELECT
    CUSTOMER_ID,
    GENDER,
    SENIOR_CITIZEN,
    PARTNER,
    DEPENDENTS,
    TENURE,
    PHONE_SERVICE,
    MULTIPLE_LINES,
    INTERNET_SERVICE,
    ONLINE_SECURITY,
    ONLINE_BACKUP,
    DEVICE_PROTECTION,
    TECH_SUPPORT,
    STREAMING_TV,
    STREAMING_MOVIES,
    CONTRACT,
    PAPERLESS_BILLING,
    PAYMENT_METHOD,
    CAST(NULLIF(TRIM(MONTHLY_CHARGES), '') AS NUMBER(12,2)) AS MONTHLY_CHARGES,
    CAST(NULLIF(TRIM(TOTAL_CHARGES), '') AS NUMBER(12,2)) AS TOTAL_CHARGES,
    CHURN,
    LOAD_DATE
FROM {{ source('raw', 'raw_customers') }}