{{ config(
    materialized='view'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'raw_network_outages') }}
)

SELECT
    TRIM(OUTAGE_ID) AS OUTAGE_ID,
    TRIM(TOWER_ID) AS TOWER_ID,
    CAST(OUTAGE_START AS TIMESTAMP_NTZ) AS OUTAGE_START,
    CAST(OUTAGE_END AS TIMESTAMP_NTZ) AS OUTAGE_END,
    CAST(DURATION_MINUTES AS NUMBER(10,0)) AS DURATION_MINUTES,
    TRIM(SEVERITY) AS SEVERITY,
    TRIM(CAUSE) AS CAUSE,
    CAST(ESTIMATED_IMPACTED_USERS AS NUMBER(10,0)) AS ESTIMATED_IMPACTED_USERS,
    LOAD_DATE
FROM source
