USE DATABASE TELECOM_DB;
USE SCHEMA RAW;

COPY INTO RAW_CUSTOMERS
(
    CUSTOMER_ID,
    GENDER,
    SENIOR_CITIZEN,
    PARTNER,
    DEPENDENTS,
    TENURE,
    PHONE_SERVICE,
    MULTIPLE_LINES,
    INTERNET_SERVICE,
    ONLINE_SECURITY,
    ONLINE_BACKUP,
    DEVICE_PROTECTION,
    TECH_SUPPORT,
    STREAMING_TV,
    STREAMING_MOVIES,
    CONTRACT,
    PAPERLESS_BILLING,
    PAYMENT_METHOD,
    MONTHLY_CHARGES,
    TOTAL_CHARGES,
    CHURN
)
FROM @CRM_STAGE/customer_churn.csv
FILE_FORMAT = (
    FORMAT_NAME = CSV_FILE_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';