-- =====================================================
-- PROJECT : Telecom Analytics Platform
-- PURPOSE : COPY INTO Commands for Snowflake RAW Layer
-- =====================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;
USE SCHEMA RAW;

-- 1. COPY RAW_CUSTOMERS
COPY INTO RAW_CUSTOMERS (
    CUSTOMER_ID, GENDER, SENIOR_CITIZEN, PARTNER, DEPENDENTS, TENURE,
    PHONE_SERVICE, MULTIPLE_LINES, INTERNET_SERVICE, ONLINE_SECURITY,
    ONLINE_BACKUP, DEVICE_PROTECTION, TECH_SUPPORT, STREAMING_TV,
    STREAMING_MOVIES, CONTRACT, PAPERLESS_BILLING, PAYMENT_METHOD,
    MONTHLY_CHARGES, TOTAL_CHARGES, CHURN
)
FROM @CRM_STAGE/customer_churn.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 2. COPY RAW_PLANS
COPY INTO RAW_PLANS (
    PLAN_ID, PLAN_NAME, MONTHLY_PRICE, DATA_LIMIT_GB,
    NETWORK_TYPE, VOICE_MINUTES, SMS_LIMIT, VALIDITY_DAYS, PLAN_CATEGORY
)
FROM @CRM_STAGE/plans.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 3. COPY RAW_TOWERS
COPY INTO RAW_TOWERS (
    TOWER_ID, TOWER_NAME, CITY, STATE, LATITUDE, LONGITUDE,
    TECHNOLOGY, VENDOR, CAPACITY, INSTALLATION_DATE, STATUS
)
FROM @CRM_STAGE/towers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 4. COPY RAW_BILLING
COPY INTO RAW_BILLING (
    BILL_ID, CUSTOMER_ID, BILLING_PERIOD, BILL_DATE, DUE_DATE,
    BASE_AMOUNT, ADDITIONAL_CHARGES, DISCOUNT_AMOUNT, TAX_AMOUNT,
    TOTAL_AMOUNT, PAYMENT_STATUS
)
FROM @CRM_STAGE/customer_billing.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 5. COPY RAW_PAYMENTS
COPY INTO RAW_PAYMENTS (
    PAYMENT_ID, BILL_ID, CUSTOMER_ID, PAYMENT_DATETIME, AMOUNT,
    PAYMENT_METHOD, PAYMENT_GATEWAY, TRANSACTION_STATUS, TRANSACTION_REF
)
FROM @CRM_STAGE/customer_payments.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 6. COPY RAW_USAGE
COPY INTO RAW_USAGE (
    USAGE_ID, CUSTOMER_ID, USAGE_DATE, TOWER_ID, VOICE_MINUTES,
    DATA_USAGE_MB, DATA_USAGE_GB, SMS_COUNT, IS_ROAMING
)
FROM @CRM_STAGE/daily_usage.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 7. COPY RAW_SUPPORT_TICKETS
COPY INTO RAW_SUPPORT_TICKETS (
    TICKET_ID, CUSTOMER_ID, CATEGORY, PRIORITY, CHANNEL,
    CREATED_AT, RESOLVED_AT, RESOLUTION_TIME_HOURS, STATUS, SATISFACTION_SCORE
)
FROM @CRM_STAGE/support_tickets.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- 8. COPY RAW_NETWORK_OUTAGES
COPY INTO RAW_NETWORK_OUTAGES (
    OUTAGE_ID, TOWER_ID, OUTAGE_START, OUTAGE_END,
    DURATION_MINUTES, SEVERITY, CAUSE, ESTIMATED_IMPACTED_USERS
)
FROM @CRM_STAGE/tower_outages.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';