-- =====================================================
-- PROJECT : Telecom Analytics Platform
-- PURPOSE : Snowflake RAW Layer Data Validation & Audits
-- =====================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;
USE SCHEMA RAW;

-- 1. Check Staged Files
LIST @CRM_STAGE;

-- 2. Verify Table Row Counts
SELECT 'RAW_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_CUSTOMERS
UNION ALL
SELECT 'RAW_PLANS', COUNT(*) FROM RAW_PLANS
UNION ALL
SELECT 'RAW_TOWERS', COUNT(*) FROM RAW_TOWERS
UNION ALL
SELECT 'RAW_BILLING', COUNT(*) FROM RAW_BILLING
UNION ALL
SELECT 'RAW_PAYMENTS', COUNT(*) FROM RAW_PAYMENTS
UNION ALL
SELECT 'RAW_USAGE', COUNT(*) FROM RAW_USAGE
UNION ALL
SELECT 'RAW_SUPPORT_TICKETS', COUNT(*) FROM RAW_SUPPORT_TICKETS
UNION ALL
SELECT 'RAW_NETWORK_OUTAGES', COUNT(*) FROM RAW_NETWORK_OUTAGES
ORDER BY TABLE_NAME;

-- 3. Check for NULL Primary Keys
SELECT 'RAW_CUSTOMERS NULL IDs' AS CHECK_TYPE, COUNT(*) AS FAILURE_COUNT FROM RAW_CUSTOMERS WHERE CUSTOMER_ID IS NULL
UNION ALL
SELECT 'RAW_PLANS NULL IDs', COUNT(*) FROM RAW_PLANS WHERE PLAN_ID IS NULL
UNION ALL
SELECT 'RAW_TOWERS NULL IDs', COUNT(*) FROM RAW_TOWERS WHERE TOWER_ID IS NULL
UNION ALL
SELECT 'RAW_BILLING NULL IDs', COUNT(*) FROM RAW_BILLING WHERE BILL_ID IS NULL
UNION ALL
SELECT 'RAW_PAYMENTS NULL IDs', COUNT(*) FROM RAW_PAYMENTS WHERE PAYMENT_ID IS NULL
UNION ALL
SELECT 'RAW_USAGE NULL IDs', COUNT(*) FROM RAW_USAGE WHERE USAGE_ID IS NULL
UNION ALL
SELECT 'RAW_SUPPORT NULL IDs', COUNT(*) FROM RAW_SUPPORT_TICKETS WHERE TICKET_ID IS NULL
UNION ALL
SELECT 'RAW_OUTAGES NULL IDs', COUNT(*) FROM RAW_NETWORK_OUTAGES WHERE OUTAGE_ID IS NULL;

-- 4. Customer Churn Distribution in RAW
SELECT 
    CHURN,
    COUNT(*) AS TOTAL_CUSTOMERS,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM RAW_CUSTOMERS
GROUP BY CHURN;

-- 5. Inspect Recent Load History
SELECT 
    TABLE_NAME,
    FILE_NAME,
    ROW_COUNT,
    STATUS,
    FIRST_ERROR_MESSAGE
FROM INFORMATION_SCHEMA.LOAD_HISTORY
WHERE SCHEMA_NAME = 'RAW'
ORDER BY LAST_LOAD_TIME DESC
LIMIT 20;
