-- =====================================================
-- PROJECT : Telecom Analytics Platform
-- PURPOSE : Business Intelligence & Analytics Queries
-- =====================================================

USE WAREHOUSE TELECOM_WH;
USE DATABASE TELECOM_DB;

-- =====================================================
-- 1. CHURN RATE BY CONTRACT TYPE & PAYMENT METHOD
-- =====================================================
SELECT 
    c.CONTRACT,
    c.PAYMENT_METHOD,
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN c.CHURN = 'Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
    ROUND(SUM(CASE WHEN c.CHURN = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CHURN_RATE_PCT,
    ROUND(AVG(c.MONTHLY_CHARGES), 2) AS AVG_MONTHLY_CHARGES
FROM TELECOM_DB.RAW.RAW_CUSTOMERS c
GROUP BY c.CONTRACT, c.PAYMENT_METHOD
ORDER BY CHURN_RATE_PCT DESC;

-- =====================================================
-- 2. AVERAGE REVENUE PER USER (ARPU) & TENURE COHORT
-- =====================================================
SELECT 
    CASE 
        WHEN TENURE <= 12 THEN '01. 0 - 1 Year'
        WHEN TENURE <= 24 THEN '02. 1 - 2 Years'
        WHEN TENURE <= 48 THEN '03. 2 - 4 Years'
        ELSE '04. 4+ Years'
    END AS TENURE_COHORT,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(MONTHLY_CHARGES), 2) AS ARPU_MONTHLY,
    ROUND(SUM(MONTHLY_CHARGES), 2) AS TOTAL_MONTHLY_REVENUE,
    ROUND(SUM(CASE WHEN CHURN = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CHURN_RATE_PCT
FROM TELECOM_DB.RAW.RAW_CUSTOMERS
GROUP BY 1
ORDER BY 1;

-- =====================================================
-- 3. CELL TOWER NETWORK OUTAGE IMPACT ON CUSTOMER CHURN
-- =====================================================
SELECT 
    t.CITY,
    t.TECHNOLOGY,
    t.VENDOR,
    COUNT(DISTINCT t.TOWER_ID) AS TOTAL_TOWERS,
    COUNT(o.OUTAGE_ID) AS TOTAL_OUTAGE_INCIDENTS,
    ROUND(AVG(COALESCE(o.DURATION_MINUTES, 0)), 1) AS AVG_OUTAGE_DURATION_MIN,
    SUM(COALESCE(o.ESTIMATED_IMPACTED_USERS, 0)) AS TOTAL_USERS_IMPACTED
FROM TELECOM_DB.RAW.RAW_TOWERS t
LEFT JOIN TELECOM_DB.RAW.RAW_NETWORK_OUTAGES o
    ON t.TOWER_ID = o.TOWER_ID
GROUP BY t.CITY, t.TECHNOLOGY, t.VENDOR
ORDER BY TOTAL_OUTAGE_INCIDENTS DESC;

-- =====================================================
-- 4. CUSTOMER SUPPORT TICKETS & RESOLUTION CORRELATION
-- =====================================================
SELECT 
    s.CATEGORY,
    s.PRIORITY,
    COUNT(s.TICKET_ID) AS TICKET_COUNT,
    ROUND(AVG(s.RESOLUTION_TIME_HOURS), 1) AS AVG_RESOLUTION_HOURS,
    ROUND(AVG(s.SATISFACTION_SCORE), 2) AS AVG_CSAT,
    ROUND(SUM(CASE WHEN c.CHURN = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CHURN_PERCENT
FROM TELECOM_DB.RAW.RAW_SUPPORT_TICKETS s
LEFT JOIN TELECOM_DB.RAW.RAW_CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY s.CATEGORY, s.PRIORITY
ORDER BY TICKET_COUNT DESC;

-- =====================================================
-- 5. DAILY 5G VS 4G DATA CONSUMPTION PATTERNS
-- =====================================================
SELECT 
    t.TECHNOLOGY,
    u.USAGE_DATE,
    COUNT(DISTINCT u.CUSTOMER_ID) AS ACTIVE_SUBSCRIBERS,
    ROUND(SUM(u.DATA_USAGE_GB), 2) AS TOTAL_DATA_GB,
    ROUND(AVG(u.DATA_USAGE_GB), 2) AS AVG_DATA_PER_USER_GB,
    ROUND(AVG(u.VOICE_MINUTES), 1) AS AVG_VOICE_MINUTES
FROM TELECOM_DB.RAW.RAW_USAGE u
JOIN TELECOM_DB.RAW.RAW_TOWERS t
    ON u.TOWER_ID = t.TOWER_ID
GROUP BY t.TECHNOLOGY, u.USAGE_DATE
ORDER BY u.USAGE_DATE DESC, t.TECHNOLOGY;
