USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION TELECOM_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::155359185640:role/SnowflakeS3Role'
STORAGE_ALLOWED_LOCATIONS = (
    's3://telecom-data-platform-likith/raw/'
);