USE ROLE ACCOUNTADMIN;
USE DATABASE TELECOM_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE CRM_STAGE
URL = 's3://telecom-data-platform-likith/raw/crm/'
STORAGE_INTEGRATION = TELECOM_S3_INT
FILE_FORMAT = CSV_FILE_FORMAT;